<?php

/**
 * @file
 *
 * Installs the required objects generic solution pack.
 */

/**
 * Implements hook_install().
 *
 * @see islandora_islandora_required_objects()
 */
function islandora_generic_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_generic');
}

/**
 * Implementation of hook_uninstall.
 */
function islandora_generic_uninstall() {

}
